sudo: required
before_install:
  - sudo apt-get install libao-dev
  - ./autogen.sh
  - ./configure --with-incompatible-bdb
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
install:
  - make
