sudo: required
before_install:
  - sudo apt-get install libao-dev
  - ./autogen.sh
  - ./configure --with-inconpatable-bdb
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
install:
  - 
  
  # Go to the Root directory  
  - cd ..

# Build steps
script:
